# Generated by Django 5.2.8 on 2025-11-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteEntregas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Reporte de Entregas',
                'verbose_name_plural': 'Reportes de Entregas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReporteMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Reporte de Movimientos',
                'verbose_name_plural': 'Reportes de Movimientos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReporteStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Reporte de Stock',
                'verbose_name_plural': 'Reportes de Stock',
                'managed': False,
            },
        ),
    ]
