# Generated by Django 5.2.8 on 2025-11-29 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporteentregas',
            options={},
        ),
    ]
