# Generated by Django 5.2.8 on 2025-11-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_alter_reporteentregas_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporteentregas',
            options={'managed': False, 'verbose_name': 'Reporte de Entregas', 'verbose_name_plural': 'Reportes de Entregas'},
        ),
    ]
