# Generated by Django 5.2.8 on 2025-12-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_alter_reporteentregas_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteStockReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Reporte de Stock Real',
                'verbose_name_plural': 'Reportes de Stock Real',
                'managed': False,
            },
        ),
    ]
