# Generated by Django 5.2.8 on 2025-12-12 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_reportestockreal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporteentregas',
            options={'managed': False, 'verbose_name': 'Reporte de Entregas', 'verbose_name_plural': '6.3. Reporte Exclusivo de Movimientos de Clientes / Beneficiarios'},
        ),
        migrations.AlterModelOptions(
            name='reportemovimiento',
            options={'managed': False, 'verbose_name': 'Reporte de Movimientos', 'verbose_name_plural': '6.1. Reporte de Movimientos de Almacenes y Clientes'},
        ),
        migrations.AlterModelOptions(
            name='reportestock',
            options={'managed': False, 'verbose_name': 'Reporte de Stock', 'verbose_name_plural': '6.2. Reporte Exclusivo de Movimientos de Almacenes'},
        ),
        migrations.AlterModelOptions(
            name='reportestockreal',
            options={'managed': False, 'verbose_name': 'Reporte de Stock Real', 'verbose_name_plural': '6.4. Reporte de Stock Real de Almacenes'},
        ),
    ]
