# Generated by Django 5.2.8 on 2025-12-13 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacenes', '0008_add_performance_indexes'),
        ('productos', '0009_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_bueno', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Stock Bueno')),
                ('stock_danado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Stock Dañado')),
                ('stock_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Stock Total')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen', verbose_name='Almacén')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Stock Cache',
                'verbose_name_plural': 'Stock Cache',
                'indexes': [models.Index(fields=['producto'], name='stock_cache_prod_idx'), models.Index(fields=['almacen'], name='stock_cache_alm_idx'), models.Index(fields=['producto', 'almacen'], name='stock_cache_prod_alm_idx'), models.Index(fields=['stock_total'], name='stock_cache_total_idx'), models.Index(fields=['ultima_actualizacion'], name='stock_cache_update_idx')],
                'unique_together': {('producto', 'almacen')},
            },
        ),
    ]
