# Generated by Django 5.2.8 on 2025-12-13 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_cache', '0001_initial'),
    ]

    operations = [
        # La población inicial se hará con un comando de management separado
        # para evitar problemas de rendimiento en la migración
    ]
