# Generated by Django 5.2.8 on 2025-12-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcionistas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepcionista',
            name='nombre',
            field=models.CharField(max_length=150, unique=True, verbose_name='* Nombre'),
        ),
    ]
