# Generated by Django 5.2.8 on 2025-12-12 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepcionistas', '0002_alter_recepcionista_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recepcionista',
            options={'ordering': ['nombre'], 'verbose_name': 'Recepcionista', 'verbose_name_plural': '5.1. Recepcionistas / Encargados'},
        ),
    ]
