# Generated by Django 5.2.8 on 2025-12-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcionistas', '0003_alter_recepcionista_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recepcionista',
            index=models.Index(fields=['nombre'], name='recepcionis_nombre_51d7d5_idx'),
        ),
        migrations.AddIndex(
            model_name='recepcionista',
            index=models.Index(fields=['activo'], name='recepcionis_activo_5105df_idx'),
        ),
        migrations.AddIndex(
            model_name='recepcionista',
            index=models.Index(fields=['email'], name='recepcionis_email_ef1ad8_idx'),
        ),
    ]
