# Generated by Django 5.2.8 on 2025-11-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_options_producto_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('INSUMOS', 'Insumos'), ('EQUIPOS', 'Equipos'), ('HERRAMIENTAS', 'Herramientas'), ('OTROS', 'Otros')], max_length=20, verbose_name='Tipo de Producto'),
        ),
    ]
