# Generated by Django 5.2.8 on 2025-11-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_codigo_alter_producto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(editable=False, help_text='Se genera automáticamente según el tipo', max_length=20, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('INSUMOS', 'Insumos'), ('EQUIPOS', 'Equipos'), ('HERRAMIENTAS', 'Herramientas'), ('OTROS', 'Otros')], help_text='Seleccione el tipo para generar el código automáticamente', max_length=20, verbose_name='Tipo de Producto'),
        ),
    ]
