# Generated by Django 5.2.8 on 2025-12-12 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_categoria_options_alter_unidadmedida_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': '3.1. Categorías'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['tipo', 'codigo'], 'verbose_name': 'Producto', 'verbose_name_plural': '3.3. Productos'},
        ),
        migrations.AlterModelOptions(
            name='unidadmedida',
            options={'verbose_name': 'Unidad de Medida', 'verbose_name_plural': '3.2. Unidades de Medida'},
        ),
    ]
