# Generated by Django 5.2.8 on 2025-12-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_alter_categoria_options_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['nombre'], name='productos_c_nombre_8571f2_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['tipo'], name='productos_p_tipo_77adae_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo'], name='productos_p_codigo_bbe51f_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria'], name='productos_p_categor_17b5fc_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['unidad_medida'], name='productos_p_unidad__100ae9_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo'], name='productos_p_activo_31f808_idx'),
        ),
        migrations.AddIndex(
            model_name='unidadmedida',
            index=models.Index(fields=['abreviatura'], name='productos_u_abrevia_f675e0_idx'),
        ),
    ]
