# Generated by Django 5.2.8 on 2025-12-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_categoria_productos_c_nombre_8571f2_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='producto',
            new_name='productos_p_codigo_idx',
            old_name='productos_p_codigo_bbe51f_idx',
        ),
        migrations.RenameIndex(
            model_name='producto',
            new_name='productos_p_tipo_idx',
            old_name='productos_p_tipo_77adae_idx',
        ),
        migrations.RenameIndex(
            model_name='producto',
            new_name='productos_p_categoria_idx',
            old_name='productos_p_categor_17b5fc_idx',
        ),
        migrations.RenameIndex(
            model_name='producto',
            new_name='productos_p_unidad_idx',
            old_name='productos_p_unidad__100ae9_idx',
        ),
        migrations.RenameIndex(
            model_name='producto',
            new_name='productos_p_activo_idx',
            old_name='productos_p_activo_31f808_idx',
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='productos_p_nombre_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['tipo', 'categoria'], name='productos_p_tipo_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo', 'tipo'], name='productos_p_activo_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria', 'activo'], name='productos_p_cat_activo_idx'),
        ),
    ]
