# Generated by Django 5.2.8 on 2025-11-24 07:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('proveedores', '0001_initial'),
        ('recepcionistas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('TRASLADO', 'Traslado entre almacenes')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('numero_movimiento', models.CharField(editable=False, max_length=50, unique=True, verbose_name='N° de movimiento')),
                ('observaciones_movimiento', models.TextField(blank=True, null=True, verbose_name='Observaciones del Movimiento')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario general')),
                ('almacen_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='almacenes.almacen', verbose_name='Almacén Destino')),
                ('almacen_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='almacenes.almacen', verbose_name='Almacén Origen')),
                ('proveedor', models.ForeignKey(blank=True, help_text='Proveedor/transporte del que se reciben los productos', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_almacen', to='proveedores.proveedor', verbose_name='Proveedor')),
                ('recepcionista', models.ForeignKey(blank=True, help_text='Persona que recepciona el movimiento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_almacen', to='recepcionistas.recepcionista', verbose_name='Recepcionista')),
            ],
            options={
                'verbose_name': 'Movimiento de Almacén',
                'verbose_name_plural': 'Movimientos de Almacén',
                'ordering': ['tipo', '-numero_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='DetalleMovimientoAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad en buen estado')),
                ('cantidad_danada', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad dañada')),
                ('observaciones_producto', models.TextField(blank=True, null=True, verbose_name='Observaciones del producto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto', verbose_name='Producto')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='almacenes.movimientoalmacen', verbose_name='Movimiento')),
            ],
            options={
                'verbose_name': 'Detalle de Movimiento',
                'verbose_name_plural': 'Detalles de Movimientos',
                'ordering': ['movimiento__tipo', '-movimiento__numero_movimiento', 'id'],
                'unique_together': {('movimiento', 'producto')},
            },
        ),
    ]
