# Generated by Django 5.2.8 on 2025-11-25 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0001_initial'),
        ('productos', '0005_alter_producto_codigo_alter_producto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_buena', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock en buen estado')),
                ('stock_danada', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock dañado')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='almacenes.almacen', verbose_name='Almacén')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['almacen__nombre', 'producto__codigo'],
                'unique_together': {('almacen', 'producto')},
            },
        ),
    ]
