# Generated by Django 5.2.8 on 2025-11-29 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0002_almacen_codigo_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
