# Generated by Django 5.2.8 on 2025-12-03 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0003_delete_stock'),
        ('proveedores', '0001_initial'),
        ('recepcionistas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoalmacen',
            name='proveedor',
            field=models.ForeignKey(help_text='Proveedor del que se reciben los productos', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_almacen', to='proveedores.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='movimientoalmacen',
            name='recepcionista',
            field=models.ForeignKey(help_text='Persona que recepciona el movimiento', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_almacen', to='recepcionistas.recepcionista', verbose_name='Recepcionista'),
        ),
    ]
