# Generated by Django 5.2.8 on 2025-12-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0004_alter_movimientoalmacen_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='codigo',
            field=models.CharField(max_length=20, unique=True, verbose_name='Código'),
        ),
    ]
