# Generated by Django 5.2.8 on 2025-12-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0005_alter_almacen_codigo'),
        ('productos', '0007_alter_categoria_options_alter_producto_options_and_more'),
        ('proveedores', '0003_alter_proveedor_options'),
        ('recepcionistas', '0003_alter_recepcionista_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='almacen',
            options={'ordering': ['nombre'], 'verbose_name': 'Almacén', 'verbose_name_plural': '1.1. Almacenes'},
        ),
        migrations.AlterModelOptions(
            name='detallemovimientoalmacen',
            options={'ordering': ['movimiento__tipo', '-movimiento__numero_movimiento', 'id'], 'verbose_name': 'Detalle de Movimiento', 'verbose_name_plural': '1.3. Detalles de Movimientos'},
        ),
        migrations.AlterModelOptions(
            name='movimientoalmacen',
            options={'ordering': ['tipo', '-numero_movimiento'], 'verbose_name': 'Movimiento de Almacén', 'verbose_name_plural': '1.2. Movimientos de Almacén'},
        ),
        migrations.AddIndex(
            model_name='detallemovimientoalmacen',
            index=models.Index(fields=['producto'], name='almacenes_d_product_dac9b9_idx'),
        ),
        migrations.AddIndex(
            model_name='detallemovimientoalmacen',
            index=models.Index(fields=['movimiento'], name='almacenes_d_movimie_37f1bc_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoalmacen',
            index=models.Index(fields=['fecha'], name='almacenes_m_fecha_4cd5b9_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoalmacen',
            index=models.Index(fields=['tipo'], name='almacenes_m_tipo_365d44_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoalmacen',
            index=models.Index(fields=['almacen_origen'], name='almacenes_m_almacen_9ad360_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoalmacen',
            index=models.Index(fields=['almacen_destino'], name='almacenes_m_almacen_0bc1b7_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoalmacen',
            index=models.Index(fields=['proveedor'], name='almacenes_m_proveed_c24978_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoalmacen',
            index=models.Index(fields=['recepcionista'], name='almacenes_m_recepci_0e1e4a_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoalmacen',
            index=models.Index(fields=['fecha', 'tipo'], name='almacenes_m_fecha_378531_idx'),
        ),
    ]
