# Generated by Django 5.2.8 on 2025-12-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0006_alter_almacen_options_and_more'),
        ('productos', '0008_categoria_productos_c_nombre_8571f2_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='detallemovimientoalmacen',
            index=models.Index(fields=['producto', 'movimiento'], name='almacenes_d_product_2b518b_idx'),
        ),
        migrations.AddIndex(
            model_name='detallemovimientoalmacen',
            index=models.Index(fields=['movimiento', 'producto'], name='almacenes_d_movimie_3b8c90_idx'),
        ),
    ]
