# Generated by Django 5.2.8 on 2025-12-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0007_detallemovimientoalmacen_almacenes_d_product_2b518b_idx_and_more'),
        ('productos', '0009_add_performance_indexes'),
        ('proveedores', '0004_proveedor_proveedores_nombre_22fb8e_idx_and_more'),
        ('recepcionistas', '0004_recepcionista_recepcionis_nombre_51d7d5_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='detallemovimientoalmacen',
            new_name='det_mov_alm_prod_idx',
            old_name='almacenes_d_product_dac9b9_idx',
        ),
        migrations.RenameIndex(
            model_name='detallemovimientoalmacen',
            new_name='det_mov_alm_mov_idx',
            old_name='almacenes_d_movimie_37f1bc_idx',
        ),
        migrations.RenameIndex(
            model_name='detallemovimientoalmacen',
            new_name='det_mov_alm_prod_mov_idx',
            old_name='almacenes_d_product_2b518b_idx',
        ),
        migrations.RenameIndex(
            model_name='detallemovimientoalmacen',
            new_name='det_mov_alm_mov_prod_idx',
            old_name='almacenes_d_movimie_3b8c90_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientoalmacen',
            new_name='mov_alm_fecha_idx',
            old_name='almacenes_m_fecha_4cd5b9_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientoalmacen',
            new_name='mov_alm_tipo_idx',
            old_name='almacenes_m_tipo_365d44_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientoalmacen',
            new_name='mov_alm_orig_idx',
            old_name='almacenes_m_almacen_9ad360_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientoalmacen',
            new_name='mov_alm_dest_idx',
            old_name='almacenes_m_almacen_0bc1b7_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientoalmacen',
            new_name='mov_alm_prov_idx',
            old_name='almacenes_m_proveed_c24978_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientoalmacen',
            new_name='mov_alm_rec_idx',
            old_name='almacenes_m_recepci_0e1e4a_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientoalmacen',
            new_name='mov_alm_fecha_tipo_idx',
            old_name='almacenes_m_fecha_378531_idx',
        ),
        migrations.AddIndex(
            model_name='almacen',
            index=models.Index(fields=['activo'], name='almacen_activo_idx'),
        ),
        migrations.AddIndex(
            model_name='almacen',
            index=models.Index(fields=['codigo'], name='almacen_codigo_idx'),
        ),
        migrations.AddIndex(
            model_name='almacen',
            index=models.Index(fields=['nombre'], name='almacen_nombre_idx'),
        ),
        migrations.AddIndex(
            model_name='almacen',
            index=models.Index(fields=['activo', 'codigo'], name='almacen_act_cod_idx'),
        ),
        migrations.AddIndex(
            model_name='detallemovimientoalmacen',
            index=models.Index(fields=['producto', 'cantidad'], name='det_mov_alm_prod_cant_idx'),
        ),
        migrations.AddIndex(
            model_name='detallemovimientoalmacen',
            index=models.Index(fields=['producto', 'cantidad_danada'], name='det_mov_alm_prod_dan_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoalmacen',
            index=models.Index(fields=['tipo', 'almacen_origen'], name='mov_alm_tipo_orig_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoalmacen',
            index=models.Index(fields=['tipo', 'almacen_destino'], name='mov_alm_tipo_dest_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoalmacen',
            index=models.Index(fields=['almacen_origen', 'almacen_destino'], name='mov_alm_orig_dest_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoalmacen',
            index=models.Index(fields=['fecha', 'almacen_origen'], name='mov_alm_fecha_orig_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoalmacen',
            index=models.Index(fields=['fecha', 'almacen_destino'], name='mov_alm_fecha_dest_idx'),
        ),
    ]
