# Generated by Django 5.2.8 on 2025-12-12 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_alter_proveedor_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre'], 'verbose_name': 'Proveedor', 'verbose_name_plural': '4.1. Proveedores / Transporte'},
        ),
    ]
