# Generated by Django 5.2.8 on 2025-12-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_alter_proveedor_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['nombre'], name='proveedores_nombre_22fb8e_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['activo'], name='proveedores_activo_4d66a6_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['email'], name='proveedores_email_32ede8_idx'),
        ),
    ]
