# Generated by Django 5.2.8 on 2025-11-24 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacenes', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(verbose_name='Cantidad')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada desde almacén'), ('SALIDA', 'Salida hacia cliente'), ('TRASLADO', 'Traslado entre clientes')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen', verbose_name='Almacén')),
                ('cliente_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='beneficiarios.cliente', verbose_name='Cliente Destino')),
                ('cliente_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='beneficiarios.cliente', verbose_name='Cliente Origen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Cliente',
                'verbose_name_plural': 'Movimientos de Cliente',
                'ordering': ['-fecha'],
            },
        ),
    ]
