# Generated by Django 5.2.8 on 2025-11-25 02:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0001_initial'),
        ('beneficiarios', '0002_alter_cliente_options_remove_cliente_email_and_more'),
        ('productos', '0005_alter_producto_codigo_alter_producto_tipo'),
        ('proveedores', '0001_initial'),
        ('recepcionistas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientocliente',
            options={'ordering': ['cliente__codigo', 'tipo', '-numero_movimiento'], 'verbose_name': 'Movimiento de Cliente', 'verbose_name_plural': 'Movimientos de Cliente'},
        ),
        migrations.RemoveField(
            model_name='movimientocliente',
            name='almacen',
        ),
        migrations.RemoveField(
            model_name='movimientocliente',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='movimientocliente',
            name='producto',
        ),
        migrations.AddField(
            model_name='movimientocliente',
            name='almacen_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas_cliente', to='almacenes.almacen', verbose_name='Almacén Destino'),
        ),
        migrations.AddField(
            model_name='movimientocliente',
            name='almacen_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salidas_cliente', to='almacenes.almacen', verbose_name='Almacén Origen'),
        ),
        migrations.AddField(
            model_name='movimientocliente',
            name='cliente',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='beneficiarios.cliente', verbose_name='Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientocliente',
            name='numero_movimiento',
            field=models.CharField(default=1, editable=False, max_length=50, unique=True, verbose_name='N° de movimiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientocliente',
            name='observaciones_movimiento',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones del Movimiento'),
        ),
        migrations.AddField(
            model_name='movimientocliente',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Proveedor del que se reciben los productos (opcional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_cliente', to='proveedores.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='movimientocliente',
            name='recepcionista',
            field=models.ForeignKey(blank=True, help_text='Persona que recepciona el movimiento (opcional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_cliente', to='recepcionistas.recepcionista', verbose_name='Recepcionista'),
        ),
        migrations.AlterField(
            model_name='movimientocliente',
            name='comentario',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario general'),
        ),
        migrations.AlterField(
            model_name='movimientocliente',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='movimientocliente',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada desde almacén'), ('SALIDA', 'Salida hacia almacén'), ('TRASLADO', 'Traslado entre clientes')], max_length=20, verbose_name='Tipo de Movimiento'),
        ),
        migrations.CreateModel(
            name='DetalleMovimientoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad en buen estado')),
                ('cantidad_danada', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad dañada')),
                ('observaciones_producto', models.TextField(blank=True, null=True, verbose_name='Observaciones del producto')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='beneficiarios.movimientocliente', verbose_name='Movimiento')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Movimiento',
                'verbose_name_plural': 'Detalles de Movimientos',
                'ordering': ['movimiento__cliente__codigo', 'movimiento__tipo', '-movimiento__numero_movimiento', 'id'],
                'unique_together': {('movimiento', 'producto')},
            },
        ),
    ]
