# Generated by Django 5.2.8 on 2025-12-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0003_alter_movimientocliente_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(verbose_name='Dirección/Comunidad'),
        ),
    ]
