# Generated by Django 5.2.8 on 2025-12-04 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0004_alter_cliente_direccion'),
        ('proveedores', '0002_alter_proveedor_nombre'),
        ('recepcionistas', '0002_alter_recepcionista_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocliente',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Proveedor/Transporte del que se reciben los productos', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_cliente', to='proveedores.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='movimientocliente',
            name='recepcionista',
            field=models.ForeignKey(blank=True, help_text='Persona que recepciona el movimiento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_cliente', to='recepcionistas.recepcionista', verbose_name='Recepcionista'),
        ),
    ]
