# Generated by Django 5.2.8 on 2025-12-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0006_alter_almacen_options_and_more'),
        ('beneficiarios', '0005_alter_movimientocliente_proveedor_and_more'),
        ('productos', '0007_alter_categoria_options_alter_producto_options_and_more'),
        ('proveedores', '0003_alter_proveedor_options'),
        ('recepcionistas', '0003_alter_recepcionista_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['codigo'], 'verbose_name': 'Cliente', 'verbose_name_plural': '2.1. Clientes / Beneficiarios'},
        ),
        migrations.AlterModelOptions(
            name='detallemovimientocliente',
            options={'ordering': ['movimiento__cliente__codigo', 'movimiento__tipo', '-movimiento__numero_movimiento', 'id'], 'verbose_name': 'Detalle de Movimiento', 'verbose_name_plural': '2.3. Detalles de Movimientos'},
        ),
        migrations.AlterModelOptions(
            name='movimientocliente',
            options={'ordering': ['cliente__codigo', 'tipo', '-numero_movimiento'], 'verbose_name': 'Movimiento de Cliente', 'verbose_name_plural': '2.2 Movimientos de Cliente / Beneficiario'},
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nombre'], name='beneficiari_nombre_75b939_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['activo'], name='beneficiari_activo_1be35b_idx'),
        ),
        migrations.AddIndex(
            model_name='detallemovimientocliente',
            index=models.Index(fields=['producto'], name='beneficiari_product_4e2a22_idx'),
        ),
        migrations.AddIndex(
            model_name='detallemovimientocliente',
            index=models.Index(fields=['movimiento'], name='beneficiari_movimie_1c4480_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocliente',
            index=models.Index(fields=['fecha'], name='beneficiari_fecha_4a22cc_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocliente',
            index=models.Index(fields=['tipo'], name='beneficiari_tipo_aec241_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocliente',
            index=models.Index(fields=['cliente'], name='beneficiari_cliente_baa9bb_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocliente',
            index=models.Index(fields=['cliente_origen'], name='beneficiari_cliente_15e8ef_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocliente',
            index=models.Index(fields=['cliente_destino'], name='beneficiari_cliente_d4e444_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocliente',
            index=models.Index(fields=['almacen_origen'], name='beneficiari_almacen_e2dbf1_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocliente',
            index=models.Index(fields=['almacen_destino'], name='beneficiari_almacen_2efcf1_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocliente',
            index=models.Index(fields=['fecha', 'tipo'], name='beneficiari_fecha_273af9_idx'),
        ),
    ]
