# Generated by Django 5.2.8 on 2025-12-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0008_add_performance_indexes'),
        ('beneficiarios', '0006_alter_cliente_options_and_more'),
        ('productos', '0009_add_performance_indexes'),
        ('proveedores', '0004_proveedor_proveedores_nombre_22fb8e_idx_and_more'),
        ('recepcionistas', '0004_recepcionista_recepcionis_nombre_51d7d5_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='detallemovimientocliente',
            new_name='det_mov_cli_prod_idx',
            old_name='beneficiari_product_4e2a22_idx',
        ),
        migrations.RenameIndex(
            model_name='detallemovimientocliente',
            new_name='det_mov_cli_mov_idx',
            old_name='beneficiari_movimie_1c4480_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientocliente',
            new_name='mov_cli_fecha_idx',
            old_name='beneficiari_fecha_4a22cc_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientocliente',
            new_name='mov_cli_tipo_idx',
            old_name='beneficiari_tipo_aec241_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientocliente',
            new_name='mov_cli_cliente_idx',
            old_name='beneficiari_cliente_baa9bb_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientocliente',
            new_name='mov_cli_orig_idx',
            old_name='beneficiari_cliente_15e8ef_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientocliente',
            new_name='mov_cli_dest_idx',
            old_name='beneficiari_cliente_d4e444_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientocliente',
            new_name='mov_cli_alm_orig_idx',
            old_name='beneficiari_almacen_e2dbf1_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientocliente',
            new_name='mov_cli_alm_dest_idx',
            old_name='beneficiari_almacen_2efcf1_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientocliente',
            new_name='mov_cli_fecha_tipo_idx',
            old_name='beneficiari_fecha_273af9_idx',
        ),
        migrations.AddIndex(
            model_name='detallemovimientocliente',
            index=models.Index(fields=['producto', 'movimiento'], name='det_mov_cli_prod_mov_idx'),
        ),
        migrations.AddIndex(
            model_name='detallemovimientocliente',
            index=models.Index(fields=['movimiento', 'producto'], name='det_mov_cli_mov_prod_idx'),
        ),
        migrations.AddIndex(
            model_name='detallemovimientocliente',
            index=models.Index(fields=['producto', 'cantidad'], name='det_mov_cli_prod_cant_idx'),
        ),
        migrations.AddIndex(
            model_name='detallemovimientocliente',
            index=models.Index(fields=['producto', 'cantidad_danada'], name='det_mov_cli_prod_dan_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocliente',
            index=models.Index(fields=['tipo', 'almacen_origen'], name='mov_cli_tipo_alm_orig_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocliente',
            index=models.Index(fields=['tipo', 'almacen_destino'], name='mov_cli_tipo_alm_dest_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocliente',
            index=models.Index(fields=['almacen_origen', 'almacen_destino'], name='mov_cli_alm_orig_dest_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocliente',
            index=models.Index(fields=['fecha', 'almacen_origen'], name='mov_cli_fecha_alm_orig_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocliente',
            index=models.Index(fields=['fecha', 'almacen_destino'], name='mov_cli_fecha_alm_dest_idx'),
        ),
    ]
